export const defaultAppLanguage = 'EN'

export const EMAIL_JS_SERVICE_ID = process.env.REACT_APP_EMAILJS_SERVICE_ID
export const EMAIL_JS_PUBLIC_KEY = process.env.REACT_APP_EMAILJS_PUBLIC_KEY
export const EMAIL_JS_TEMPLATE_ID_FOR_EMAIL = process.env.REACT_APP_EMAILJS_TEMPLATE_ID_FOR_EMAIL
export const EMAIL_JS_TEMPLATE_ID_FOR_CONTACT = process.env.REACT_APP_EMAILJS_TEMPLATE_ID_FOR_CONTACT